defaults: &defaults
  host: 127.0.0.1
  port: 27017

development:
  <<: *defaults
  database: cafretest_mysql_mongo_development

test:
  <<: *defaults
  database: cafretest_mysql_mongo_test

# set these environment variables on your prod server
production:
  <<: *defaults
  database: cafretest_mysql_mongo
  username: <%= ENV['MONGO_USERNAME'] %>
  password: <%= ENV['MONGO_PASSWORD'] %>
